//! The G1 FINAL differential boundary fixtures (`g1_integer/final/fixtures/`, 42 files generated by the oracle's
//! scalar helpers and `*_ref` kernels, staged verbatim with their arrays by `tools/export_fixtures.py` into
//! `g2_guest/fixtures_final/`), run against the Rust kernels: rounding ties at every used shift and divisor, zero and
//! negative shifts, domain endpoints, saturation in noising / convolution requantisation / add / concat / GroupNorm,
//! constant and nearly constant GroupNorm groups, the maximum group size n = 32256, isqrt of perfect squares +-1,
//! convolution impulses and stride-1/2 tails at output widths 20, 21 and 24 (the eight-column block), pooling ties,
//! bilinear borders, every lookup-table index and mask, attention equal-score / exponent-clamp / signed-average /
//! head-dim-12 cases, and the SSE endpoints. Expected values AND clip counters must match (Astra r4 item 4).

use armc_int::kernels as k;
use armc_int::loader::load_constants;
use armc_int::Tensor;
use serde_json::Value;
use std::path::PathBuf;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("fixtures_final")
}

fn load(name: &str) -> Value {
    let p = root().join(format!("{name}.json"));
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e} (run tools/export_fixtures.py)", p.display()))).unwrap()
}

fn i64s(v: &Value) -> Vec<i64> {
    let mut out = Vec::new();
    fn walk(v: &Value, out: &mut Vec<i64>) {
        match v {
            Value::Array(a) => a.iter().for_each(|x| walk(x, out)),
            Value::Number(n) => out.push(n.as_i64().expect("integer")),
            Value::String(s) => out.push(s.parse().expect("integer string")),
            other => panic!("unexpected {other}"),
        }
    }
    walk(v, &mut out);
    out
}

fn i16s(v: &Value) -> Vec<i16> {
    i64s(v).into_iter().map(|x| i16::try_from(x).expect("int16")).collect()
}

fn shape(v: &Value) -> Vec<usize> {
    let mut s = Vec::new();
    let mut cur = v;
    while let Value::Array(a) = cur {
        s.push(a.len());
        if a.is_empty() {
            break;
        }
        cur = &a[0];
    }
    s
}

/// An array given inline or as a staged npz key.
fn array_i16(fx: &Value, name: &str, sec: &str, field: &str) -> (Vec<i16>, Vec<usize>) {
    let v = &fx[sec][field];
    if let Some(key) = v.get("npz_key") {
        let idx: Value = serde_json::from_str(&std::fs::read_to_string(root().join("index.json")).unwrap()).unwrap();
        let entry = &idx["fixtures"][name]["arrays"][key.as_str().unwrap()];
        let bytes = std::fs::read(root().join(entry["file"].as_str().unwrap())).unwrap();
        let sh: Vec<usize> = entry["shape"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap() as usize).collect();
        let dt = entry["dtype"].as_str().unwrap();
        let vals: Vec<i16> = match dt {
            "i16" => bytes.chunks_exact(2).map(|c| i16::from_le_bytes([c[0], c[1]])).collect(),
            "u8" => bytes.iter().map(|&b| b as i16).collect(),
            other => panic!("dtype {other}"),
        };
        (vals, sh)
    } else {
        (i16s(v), shape(v))
    }
}

fn counter(fx: &Value, key: &str) -> u32 {
    fx["counters"][key].as_u64().unwrap_or_else(|| panic!("counter {key} missing")) as u32
}

fn exp_table() -> Vec<u32> {
    let k = load_constants(&PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("oracle_final").join("int16_d2_1328_correct"));
    k.exp_table
}

#[test]
fn fixtures_manifest_is_the_final_one() {
    let idx: Value = serde_json::from_str(&std::fs::read_to_string(root().join("index.json")).unwrap()).unwrap();
    assert_eq!(idx["checkpoint_sha256"].as_str().unwrap(), "c6955192067c8df1f46960f4803b32eac1c037b84a0f40de3b265b739d85fab8");
    assert_eq!(idx["fixtures"].as_object().unwrap().len(), 42, "42 fixtures");
}

#[test]
fn rounding_fixtures() {
    for name in ["rounding_shifts_ties", "rounding_shifts_zero_negative"] {
        let fx = load(name);
        let v = i64s(&fx["inputs"]["v"]);
        let s = i64s(&fx["inputs"]["s"]);
        let e = i64s(&fx["expected"]["rshift_round"]);
        assert_eq!(v.len(), e.len());
        for i in 0..v.len() {
            assert_eq!(k::rshift_round(v[i], s[i] as i32), e[i], "{name}: rshift_round({}, {})", v[i], s[i]);
        }
        println!("{name}: {} cases", v.len());
    }
    let fx = load("rounding_divisors_ties");
    let a = i64s(&fx["inputs"]["a"]);
    let b = i64s(&fx["inputs"]["b"]);
    let e = i64s(&fx["expected"]["round_div"]);
    for i in 0..a.len() {
        assert_eq!(k::round_div(a[i], b[i]), e[i], "round_div({}, {})", a[i], b[i]);
    }
    println!("rounding_divisors_ties: {} cases", a.len());
}

#[test]
fn domain_endpoints_clamp16() {
    let fx = load("domain_endpoints_clamp16");
    let v = i64s(&fx["inputs"]["v"]);
    let e = i16s(&fx["expected"]["clamp16"]);
    let flags = i64s(&fx["expected"]["clip_flag"]);
    let mut sat = 0u32;
    for i in 0..v.len() {
        let before = sat;
        assert_eq!(k::clamp16(v[i], &mut sat), e[i], "clamp16({})", v[i]);
        assert_eq!((sat - before) as i64, flags[i], "clip flag for {}", v[i]);
    }
    assert_eq!(sat, counter(&fx, "clip_events"));
}

#[test]
fn noising_saturation() {
    let fx = load("noising_saturation");
    let p = &fx["params"];
    let (sa, so, sh) = (p["SA_INT"].as_i64().unwrap(), p["SO_INT"].as_i64().unwrap(), p["P"].as_u64().unwrap() as u32);
    let c = i16s(&fx["inputs"]["C_int"]);
    let n = i16s(&fx["inputs"]["noise_int"]);
    let acc = i64s(&fx["expected"]["acc"]);
    let pre = i64s(&fx["expected"]["pre_clip"]);
    let ct_e = i16s(&fx["expected"]["Ct_int"]);
    for i in 0..c.len() {
        let a = sa * c[i] as i64 + so * n[i] as i64;
        assert_eq!(a, acc[i]);
        assert_eq!(k::rshift_round(a, sh as i32), pre[i], "pre-clip for ({}, {})", c[i], n[i]);
    }
    let mut sat = 0u32;
    let ct = k::noise_ct(&c, &n, sa, so, sh, &mut sat);
    assert_eq!(ct, ct_e);
    assert_eq!(sat, counter(&fx, "clip_events_C_t"));
}

fn conv_layer(name: &str, wq: &[i16], out_ch: usize, in_ch: usize, stride: usize, pad: usize, m: Vec<i64>, bp: Vec<i64>, shift: u32) -> k::ConvLayer {
    let mut l = k::ConvLayer { name: name.to_string(), out_ch, in_ch, kh: 3, kw: 3, stride, pad, f_in: 11, f_out: 11, shift, w: wq.to_vec(), m, bp, acc_bound: 0 };
    l.finalize().unwrap_or_else(|e| panic!("{name}: finalize: {e}"));
    l
}

#[test]
fn convolution_impulses_and_tails() {
    for name in ["conv3x3_impulses_s1_w20", "conv3x3_impulses_s2_w20", "conv3x3_impulses_s2_w21"] {
        let fx = load(name);
        let stride = fx["params"]["stride"].as_u64().unwrap() as usize;
        let pad = fx["params"]["pad"].as_u64().unwrap() as usize;
        let xs = fx["params"]["x_shape"].as_array().unwrap();
        let (c, h, w) = (xs[0].as_u64().unwrap() as usize, xs[1].as_u64().unwrap() as usize, xs[2].as_u64().unwrap() as usize);
        let wq = i16s(&fx["inputs"]["w"]);
        let cases = fx["inputs"]["x"].as_array().unwrap();
        let expected = fx["expected"]["acc"].as_array().unwrap();
        // M = 2, S = 1: y = (2 acc + 1) >> 1 = acc, so the blocked fast path reproduces the accumulator exactly
        let l = conv_layer(name, &wq, 1, c, stride, pad, vec![2], vec![0], 1);
        for (i, xv) in cases.iter().enumerate() {
            let x = Tensor::new(c, h, w, 11, i16s(xv));
            let e = i64s(&expected[i]);
            let (ho, wo) = l.out_shape(h, w);
            let mut acc = vec![0i64; ho * wo];
            k::conv_generic_plane(&x.v, c, h, w, 3, 3, stride, pad, &wq, &mut acc);
            assert_eq!(acc, e, "{name}: impulse {i} generic accumulator");
            let mut sat = 0u32;
            let y = k::conv2d(&x, &l, &mut sat);
            assert_eq!(y.v.iter().map(|&v| v as i64).collect::<Vec<_>>(), e, "{name}: impulse {i} blocked path");
            assert_eq!(sat, 0);
        }
        println!("{name}: {} impulses, output width {}", cases.len(), l.out_shape(h, w).1);
    }
}

#[test]
fn convolution_requantisation_random_and_saturation() {
    for name in ["conv3x3_random_int16_s1_w24", "conv3x3_random_int16_s2_w24", "conv3x3_random_int8_s1_w24", "conv3x3_random_int8_s2_w24", "conv_requant_saturation_S30", "conv_requant_saturation_S43", "conv_requant_saturation_S8"] {
        let fx = load(name);
        let stride = fx["params"]["stride"].as_u64().unwrap() as usize;
        let pad = fx["params"]["pad"].as_u64().unwrap() as usize;
        let shift = fx["params"]["S"].as_u64().unwrap() as u32;
        let xs = shape(&fx["inputs"]["x"]);
        let (c, h, w) = (xs[0], xs[1], xs[2]);
        let ws = shape(&fx["inputs"]["wq"]);
        let out_ch = ws[0];
        assert_eq!(ws[1], c);
        let wq = i16s(&fx["inputs"]["wq"]);
        let m = i64s(&fx["inputs"]["M"]);
        let bp = i64s(&fx["inputs"]["bp"]);
        let l = conv_layer(name, &wq, out_ch, c, stride, pad, m, bp, shift);
        if let Some(b) = fx["expected"].get("acc_bound_static") {
            assert_eq!(l.acc_bound, b.as_i64().unwrap(), "{name}: static accumulator bound");
        }
        let x = Tensor::new(c, h, w, 11, i16s(&fx["inputs"]["x"]));
        let (ho, wo) = l.out_shape(h, w);
        let e_acc = i64s(&fx["expected"]["acc"]);
        let per_out = c * 9;
        let mut all = Vec::new();
        for o in 0..out_ch {
            let mut acc = vec![0i64; ho * wo];
            k::conv_generic_plane(&x.v, c, h, w, 3, 3, stride, pad, &l.w[o * per_out..(o + 1) * per_out], &mut acc);
            all.extend(acc);
        }
        assert_eq!(all, e_acc, "{name}: accumulators");
        if let Some(obs) = fx["expected"].get("acc_absmax_observed") {
            assert_eq!(all.iter().map(|a| a.abs()).max().unwrap(), obs.as_i64().unwrap());
        }
        let mut sat = 0u32;
        let y = k::conv2d(&x, &l, &mut sat);
        assert_eq!(y.v, i16s(&fx["expected"]["y"]), "{name}: requantised output");
        assert_eq!(sat, counter(&fx, "clip_events"), "{name}: clip events");
        println!("{name}: {}x{}x{} -> {}x{}x{}, S {shift}, clips {sat}", c, h, w, out_ch, ho, wo);
    }
}

#[test]
fn add_and_concat_saturation() {
    let fx = load("add_saturation_rescale");
    for (key, case) in fx["inputs"].as_object().unwrap() {
        // key: a_f{fa}_b_f{fb}_fo{fo}
        let parts: Vec<&str> = key.split('_').collect();
        let fa: u32 = parts[1][1..].parse().unwrap();
        let fb: u32 = parts[3][1..].parse().unwrap();
        let fo: u32 = parts[4][2..].parse().unwrap();
        let a = i16s(&case["a"]);
        let b = i16s(&case["b"]);
        let n = a.len();
        let ta = Tensor::new(1, 1, n, fa, a);
        let tb = Tensor::new(1, 1, n, fb, b);
        let mut sat = 0u32;
        let y = k::add(&ta, &tb, fo, &mut sat);
        let suffix = &key[2..]; // f11_b_f12_fo11
        assert_eq!(y.v, i16s(&fx["expected"][format!("y_{suffix}")]), "add {key}");
        assert_eq!(sat, counter(&fx, &format!("clip_events_{suffix}")), "add {key} clips");
    }
    let fx = load("concat_saturation_rescale");
    let f = &fx["inputs"]["f"];
    let (fa, fb, fo) = (f["a"].as_u64().unwrap() as u32, f["b"].as_u64().unwrap() as u32, f["out"].as_u64().unwrap() as u32);
    let sa = shape(&fx["inputs"]["a"]);
    let sb = shape(&fx["inputs"]["b"]);
    let ta = Tensor::new(sa[0], 1, sa[1], fa, i16s(&fx["inputs"]["a"]));
    let tb = Tensor::new(sb[0], 1, sb[1], fb, i16s(&fx["inputs"]["b"]));
    let mut sat = 0u32;
    let y = k::cat(&ta, &tb, fo, &mut sat);
    assert_eq!(y.v, i16s(&fx["expected"]["y"]));
    assert_eq!(y.c, sa[0] + sb[0]);
    assert_eq!(sat, counter(&fx, "clip_events"));
}

#[test]
fn groupnorm_fixtures() {
    for name in ["groupnorm_constant_group", "groupnorm_nearly_constant_group", "groupnorm_endpoints_n84", "groupnorm_balanced_endpoints_n32256", "groupnorm_saturation_both_signs", "groupnorm_zero_gamma"] {
        let fx = load(name);
        let p = &fx["params"];
        let (groups, eps_int, t, f_out) = (p["groups"].as_u64().unwrap() as usize, p["eps_int"].as_i64().unwrap(), p["T"].as_u64().unwrap() as u32, p["f_out"].as_u64().unwrap() as u32);
        let (xv, xs) = array_i16(&fx, name, "inputs", "x");
        let (c, h, w) = (xs[0], xs[1], xs[2]);
        assert_eq!(p["n"].as_u64().unwrap() as usize, (c / groups) * h * w);
        let l = k::GnLayer { name: name.to_string(), channels: c, groups, eps_int, f_in: 12, f_out, gamma_q: i64s(&fx["inputs"]["gamma_q"]), beta_q: i64s(&fx["inputs"]["beta_q"]) };
        let x = Tensor::new(c, h, w, 12, xv);
        let mut sat = 0u32;
        let y = k::groupnorm(&x, &l, t, &mut sat);
        let (ye, _) = array_i16(&fx, name, "expected", "y");
        assert_eq!(y.v, ye, "{name}: output");
        assert_eq!(sat, counter(&fx, "clip_events"), "{name}: clip events");
        println!("{name}: n {} groups {groups} clips {sat}", p["n"]);
    }
}

#[test]
fn isqrt_perfect_squares() {
    let fx = load("isqrt_perfect_squares");
    let n: Vec<u128> = fx["inputs"]["n"].as_array().unwrap().iter().map(|s| s.as_str().unwrap().parse().unwrap()).collect();
    let e: Vec<u128> = fx["expected"]["isqrt"].as_array().unwrap().iter().map(|s| s.as_str().unwrap().parse().unwrap()).collect();
    for i in 0..n.len() {
        assert_eq!(k::isqrt_u128(n[i]), e[i], "isqrt({})", n[i]);
    }
    println!("isqrt: {} cases up to 2^102", n.len());
}

#[test]
fn pooling_and_bilinear_fixtures() {
    let fx = load("avgpool2_ties");
    let xs = shape(&fx["inputs"]["x"]);
    let x = Tensor::new(xs[0], xs[1], xs[2], 11, i16s(&fx["inputs"]["x"]));
    let mut sat = 0u32;
    let y = k::avgpool2(&x, &mut sat);
    assert_eq!(y.v, i16s(&fx["expected"]["y"]));
    assert_eq!(sat, counter(&fx, "clip_events"));
    for name in ["bilinear_up2_border_1x1", "bilinear_up2_border_2x2", "bilinear_up2_border_2x3", "bilinear_up2_border_3x3"] {
        let fx = load(name);
        let xs = shape(&fx["inputs"]["x"]);
        let x = Tensor::new(xs[0], xs[1], xs[2], 11, i16s(&fx["inputs"]["x"]));
        let mut sat = 0u32;
        let y = k::bilinear_up2(&x, &mut sat);
        assert_eq!(y.v, i16s(&fx["expected"]["y"]), "{name}");
        assert_eq!((y.c, y.h, y.w), (xs[0], 2 * xs[1], 2 * xs[2]));
        assert_eq!(sat, counter(&fx, "clip_events"), "{name}: clips");
    }
}

#[test]
fn lut_all_indices_and_masks() {
    for name in ["lut_all_indices_gelu_11_11", "lut_all_indices_silu_10_10", "lut_all_indices_silu_10_11", "lut_all_indices_silu_11_11", "lut_all_indices_silu_11_12", "lut_all_indices_silu_12_12", "lut_all_indices_silu_9_10", "lut_all_indices_silu_9_9"] {
        let fx = load(name);
        let f_out = fx["params"]["f_out"].as_u64().unwrap() as u32;
        let (xv, _) = array_i16(&fx, name, "inputs", "x");
        let (table, _) = array_i16(&fx, name, "inputs", "table");
        let (mask_u8, _) = array_i16(&fx, name, "inputs", "mask");
        let mut mask = vec![0u8; k::LUT_MASK_BYTES];
        for (i, &m) in mask_u8.iter().enumerate() {
            if m != 0 {
                mask[i >> 3] |= 1 << (i & 7);
            }
        }
        let x = Tensor::new(1, 256, 256, fx["params"]["f_in"].as_u64().unwrap() as u32, xv);
        let mut sat = 0u32;
        let y = k::lut_apply(&x, &table, &mask, f_out, &mut sat);
        let (ye, _) = array_i16(&fx, name, "expected", "y");
        assert_eq!(y.v, ye, "{name}: outputs");
        assert_eq!(sat, counter(&fx, "lut_clipped_hits"), "{name}: hits over every index");
        assert_eq!(k::lut_mask_popcount(&mask) as u64, fx["expected"]["clipped_entries"].as_u64().unwrap());
        let one = Tensor::new(1, 1, 1, x.f, vec![32767]);
        let mut hit = 0u32;
        k::lut_apply(&one, &table, &mask, f_out, &mut hit);
        assert_eq!(hit as u64, fx["expected"]["hit_for_input_32767"].as_u64().unwrap(), "{name}: hit for input 32767");
        println!("{name}: clipped entries {}, hits {sat}", k::lut_mask_popcount(&mask));
    }
}

#[test]
fn attention_fixtures() {
    let exp = exp_table();
    for name in ["attention_equal_scores", "attention_exponent_clamp_boundary", "attention_signed_weighted_average", "attention_head_dim12_multiplier"] {
        let fx = load(name);
        let p = &fx["params"];
        let (heads, d, tokens) = (p["heads"].as_u64().unwrap() as usize, p["head_dim"].as_u64().unwrap() as usize, p["tokens"].as_u64().unwrap() as usize);
        let (f, mult, r_shift) = (p["f_qkv"].as_u64().unwrap() as u32, p["mult"].as_i64().unwrap(), p["r_shift"].as_u64().unwrap() as u32);
        assert_eq!(p["exp_table_sha256_int64_le"].as_str().unwrap(), "e1978b8be2bd826ec3b939556d34dc9d6e1b9be6f1668e5f3b70ddbc52a5a706");
        let q = i16s(&fx["inputs"]["q"]);
        let kk = i16s(&fx["inputs"]["k"]);
        let v = i16s(&fx["inputs"]["v"]);
        let c = heads * d;
        assert_eq!(q.len(), c * tokens);
        let mut qkv = Vec::with_capacity(3 * c * tokens);
        qkv.extend_from_slice(&q);
        qkv.extend_from_slice(&kk);
        qkv.extend_from_slice(&v);
        let t = Tensor::new(3 * c, 1, tokens, f, qkv);
        let mut sat = 0u32;
        let out = k::attention(&t, heads, mult, r_shift, &exp, &mut sat);
        assert_eq!(out.v, i16s(&fx["expected"]["out"]), "{name}: output");
        assert_eq!(sat, counter(&fx, "clip_events"), "{name}: clips");
        println!("{name}: heads {heads} d {d} tokens {tokens} mult {mult} r_shift {r_shift}");
    }
}

#[test]
fn sse_endpoints() {
    let fx = load("sse_endpoints");
    let n = fx["params"]["elements"].as_u64().unwrap() as usize;
    assert_eq!(n, 43008);
    let e: Vec<u64> = fx["expected"]["sse"].as_array().unwrap().iter().map(|s| s.as_str().unwrap().parse().unwrap()).collect();
    let cases: Vec<(Vec<i16>, Vec<i16>)> = vec![
        (vec![-32768; n], vec![32767; n]),
        (vec![32767; n], vec![-32768; n]),
        ((0..n).map(|i| if i < n / 2 { -32768 } else { 32767 }).collect(), (0..n).map(|i| if i < n / 2 { 32767 } else { -32768 }).collect()),
        (vec![-32768; n], vec![-32768; n]),
    ];
    for (i, (eps, noise)) in cases.iter().enumerate() {
        assert_eq!(k::residual_sum(eps, noise) as u64, e[i], "sse case {i}");
    }
    assert_eq!(fx["expected"]["sse_bound"].as_str().unwrap().parse::<i64>().unwrap(), k::SSE_BOUND_96X112);
}
