//! Vector tests against `g2_guest/vectors_relation/` (generated by gen_vectors.py from the pipeline's own code
//! paths: torch area interpolation, numpy/torch float casts, the truthbeam XOF and CPU renderer, the G1 noise
//! emulation, the local d2 and August chain logs). Every file is checked against MANIFEST.json before use, so a
//! stale or edited vector fails the test rather than passing it.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use armc_relation::b3xof::{self, blake3p};
use armc_relation::beacon::verify_and_bind;
use armc_relation::emission::expand_and_digest;
use armc_relation::fp::{bf16_bits_to_f32, cache_quant, f16_bits_to_f32, f32_to_bf16_bits, f32_to_f16_bits};
use armc_relation::frame::{area_bins, quant_exact, quant_torchpath, reduce_exact, reduce_torch_f32};
use armc_relation::header::{hex, unhex, unhex32, RowWitnessHeader};
use armc_relation::hint::{coord_int, e_int_exact, e_int_torchpath, hint14, octave_grid, resize_torch_f32};
use armc_relation::membership::{open_to_wrapped_root, parse_leaf_u, parse_siblings, row_leaf_hash, LeafFields, MembershipWitness};
use armc_relation::net::StubDenoiser;
use armc_relation::noise::{forward_noise, i16_from_le, i16_to_le};
use armc_relation::spec::preprocess_spec_sha256;
use armc_relation::statement::{evaluate, PreviousRecord, PublicOutput, Witness, OFFSET_RULE_DIRECT, OFFSET_RULE_MIRRORED, PUBLIC_BYTES};
use armc_relation::{OUT_H, OUT_W, RAW_BYTES, RAW_H, RAW_W};
use sha2::{Digest, Sha256};

fn vectors_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../vectors_relation").canonicalize().expect("vectors_relation directory")
}

struct Vectors {
    dir: PathBuf,
    manifest: serde_json::Value,
}

impl Vectors {
    fn open() -> Self {
        let dir = vectors_dir();
        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("MANIFEST.json")).expect("MANIFEST.json")).unwrap();
        Self { dir, manifest }
    }

    /// Read a vector file and check its sha256 against the manifest.
    fn bytes(&self, rel: &str) -> Vec<u8> {
        let data = std::fs::read(self.dir.join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}"));
        let entry = &self.manifest["files"][rel];
        let expected = entry["sha256"].as_str().unwrap_or_else(|| panic!("{rel} not in MANIFEST.json"));
        assert_eq!(hex(&Sha256::digest(&data)), expected, "{rel} differs from MANIFEST.json");
        data
    }

    fn i16s(&self, rel: &str) -> Vec<i16> {
        i16_from_le(&self.bytes(rel)).unwrap()
    }

    fn u16s(&self, rel: &str) -> Vec<u16> {
        self.bytes(rel).chunks_exact(2).map(|c| u16::from_le_bytes([c[0], c[1]])).collect()
    }

    fn u32s(&self, rel: &str) -> Vec<u32> {
        self.bytes(rel).chunks_exact(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
    }

    fn f32s(&self, rel: &str) -> Vec<f32> {
        self.bytes(rel).chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
    }

    fn json(&self, rel: &str) -> serde_json::Value {
        serde_json::from_slice(&self.bytes(rel)).unwrap()
    }
}

// ------------------------------------------------------------------ the shared PRNG (gen_vectors.py splitmix64_stream)

fn splitmix64_at(seed: u64, i: u64) -> u64 {
    let mut z = seed.wrapping_add((i + 1).wrapping_mul(0x9E37_79B9_7F4A_7C15));
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

fn prng_bytes(seed: u64, n: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(n + 8);
    let mut i = 0_u64;
    while out.len() < n {
        out.extend_from_slice(&splitmix64_at(seed, i).to_le_bytes());
        i += 1;
    }
    out.truncate(n);
    out
}

fn synthetic_frame(kind: char) -> Vec<u8> {
    let seed = match kind {
        'a' => 0xA5A5_0001,
        'b' => 0xA5A5_0002,
        _ => unreachable!(),
    };
    let mut b = prng_bytes(seed, RAW_H * RAW_W);
    if kind == 'b' {
        for y in 0..RAW_H {
            for x in 0..RAW_W {
                let v = &mut b[y * RAW_W + x];
                if x < 1000 {
                    *v = u8::from(*v == 255);
                } else if x < 2000 {
                    *v &= 3;
                }
            }
        }
    }
    b
}

fn f32_bits_eq(a: &[f32], b: &[f32]) -> usize {
    assert_eq!(a.len(), b.len());
    a.iter().zip(b.iter()).filter(|(x, y)| x.to_bits() != y.to_bits()).count()
}

// ------------------------------------------------------------------ tests

#[test]
fn float_conversions_match_numpy_and_torch_on_8192_vectors() {
    let v = Vectors::open();
    let x = v.f32s("conv/f32_in.bin");
    let f16 = v.u16s("conv/f16_bits.bin");
    let bf16 = v.u16s("conv/bf16_bits.bin");
    let back = v.f32s("conv/f16_back_f32.bin");
    let q12 = v.i16s("conv/cache_q12.bin");
    assert_eq!(x.len(), 8192);
    for i in 0..x.len() {
        assert_eq!(f32_to_f16_bits(x[i]), f16[i], "f16 at {i}: x = {:?} ({:#010x})", x[i], x[i].to_bits());
        assert_eq!(f16_bits_to_f32(f16[i]).to_bits(), back[i].to_bits(), "f16->f32 at {i}");
        assert_eq!(f32_to_bf16_bits(x[i]), bf16[i], "bf16 at {i}: x = {:?} ({:#010x})", x[i], x[i].to_bits());
        assert_eq!(cache_quant(x[i], 12), q12[i], "cache_quant at {i}: x = {:?}", x[i]);
    }
    // the bf16 table also fixes bf16_bits_to_f32 by construction; spot check
    assert_eq!(bf16_bits_to_f32(0x3f80), 1.0);
}

#[test]
fn torch_area_bins_match_the_python_reference() {
    let v = Vectors::open();
    let j = v.json("synthetic/area_bins.json");
    let check = |key: &str, bins: Vec<(usize, usize)>| {
        let arr = j[key].as_array().unwrap();
        assert_eq!(arr.len(), bins.len(), "{key}");
        for (k, pair) in arr.iter().enumerate() {
            assert_eq!(pair[0].as_u64().unwrap() as usize, bins[k].0, "{key}[{k}] start");
            assert_eq!(pair[1].as_u64().unwrap() as usize, bins[k].1, "{key}[{k}] end");
        }
    };
    check("y_2300_to_96", area_bins(2300, OUT_H));
    check("x_2660_to_112", area_bins(2660, OUT_W));
    for h in [17_usize, 34, 68, 135] {
        let arr = j["octave_y"][h.to_string()].as_array().unwrap();
        let bins = area_bins(h, OUT_H);
        for (k, pair) in arr.iter().enumerate() {
            assert_eq!((pair[0].as_u64().unwrap() as usize, pair[1].as_u64().unwrap() as usize), bins[k]);
        }
    }
    for w in [30_usize, 60, 120, 240] {
        let arr = j["octave_x"][w.to_string()].as_array().unwrap();
        let bins = area_bins(w, OUT_W);
        for (k, pair) in arr.iter().enumerate() {
            assert_eq!((pair[0].as_u64().unwrap() as usize, pair[1].as_u64().unwrap() as usize), bins[k]);
        }
    }
}

fn synthetic_frame_case(kind: char) {
    let v = Vectors::open();
    let raw = synthetic_frame(kind);
    assert_eq!(raw.len(), RAW_BYTES);
    let note = &v.manifest["notes"][format!("synthetic_frame_{kind}")];
    assert_eq!(hex(&Sha256::digest(&raw)), note["sha256"].as_str().unwrap(), "PRNG frame {kind} differs from Python's");
    let means = reduce_torch_f32(&raw);
    let ref_means = v.f32s(&format!("synthetic/frame_{kind}_area_f32.bin"));
    assert_eq!(f32_bits_eq(&means, &ref_means), 0, "torch area means differ bitwise (frame {kind})");
    assert_eq!(quant_torchpath(&means, 12), v.i16s(&format!("synthetic/frame_{kind}_c_q12_torchpath.bin")), "C_int torch path (frame {kind})");
    let (sums, counts) = reduce_exact(&raw);
    assert_eq!(sums, v.u32s(&format!("synthetic/frame_{kind}_sums.bin")), "exact sums (frame {kind})");
    assert_eq!(counts, v.u32s(&format!("synthetic/frame_{kind}_counts.bin")), "counts (frame {kind})");
    assert_eq!(quant_exact(&sums, &counts, 12), v.i16s(&format!("synthetic/frame_{kind}_c_q12_exact.bin")), "C_int exact (frame {kind})");
    let stats = &v.manifest["notes"][format!("synthetic_frame_{kind}_stats")];
    let mism = quant_torchpath(&means, 12).iter().zip(quant_exact(&sums, &counts, 12).iter()).filter(|(a, b)| a != b).count();
    assert_eq!(mism as u64, stats["torchpath_vs_exact_q12_mismatch"].as_u64().unwrap());
}

#[test]
fn synthetic_frame_a_random_bytes_reduces_bit_exactly() {
    synthetic_frame_case('a');
}

#[test]
fn synthetic_frame_b_with_f16_subnormal_means_reduces_bit_exactly() {
    let v = Vectors::open();
    assert!(v.manifest["notes"]["synthetic_frame_b_stats"]["f16_subnormal_means"].as_u64().unwrap() > 1000);
    synthetic_frame_case('b');
}

#[test]
fn d2_rows_1328_and_1330_hints_match_the_g1_vectors() {
    let v = Vectors::open();
    let j = v.json("d2/d2_rows.json");
    // hashes of the G1 manifests (g1_integer/vectors/vectors_int16_{correct,wrong_p2}.json, inputs.E_int)
    let g1: BTreeMap<&str, &str> = [
        ("1328", "26f2fedf7b7795bbff827915f65b6bb9d21de380be0aec10979f138ba0152de6"),
        ("1330", "7ab0ee868f3c227b78d8e17f6fba8a5f2d14a2b8c9dd2cc70ca0a9029ff72484"),
    ]
    .into_iter()
    .collect();
    for (row, expected) in g1 {
        let s_t = unhex32(j["rows"][row]["S_t_hex"].as_str().unwrap());
        assert_eq!(j["rows"][row]["E_int_sha256_g1"].as_str().unwrap(), expected);
        let cond = b3xof::expand_all(&s_t);
        // the float32 means of every octave grid, bit-exact
        let ref_area = v.f32s(&format!("d2/row_00{row}_E_area_f32.bin"));
        for o in 0..4 {
            for c in 0..3 {
                let means = resize_torch_f32(octave_grid(&cond, c, o), b3xof::GRID_H[o], b3xof::GRID_W[o]);
                let ch = 3 * o + c;
                assert_eq!(f32_bits_eq(&means, &ref_area[ch * OUT_H * OUT_W..(ch + 1) * OUT_H * OUT_W]), 0, "row {row} octave {o} channel {c}");
            }
        }
        let e = e_int_torchpath(&cond);
        assert_eq!(e, v.i16s(&format!("d2/row_00{row}_E_q14_torchpath.bin")), "row {row} E_int torch path");
        assert_eq!(hex(&Sha256::digest(i16_to_le(&e))), expected, "row {row} E_int sha256 vs G1");
        assert_eq!(e_int_exact(&cond), v.i16s(&format!("d2/row_00{row}_E_q14_exact.bin")), "row {row} E_int exact");
    }
}

#[test]
fn d2_row_1328_coordinates_hint_noise_and_ct_match_g1() {
    let v = Vectors::open();
    // G1 manifest hashes (vectors_int16_correct.json: inputs.*, layers.hint)
    const COORD: &str = "8418418425e7198b0b53469918956091101477d541cedb6720400944a16b1f18";
    const HINT: &str = "b4e00b6acf621b974b5beb688f53a7fd65f5b56f47af31ced12116322c314cc3";
    const C_INT: &str = "9baf878a31ac8604c383b29b7cb3fadfc86c4edc419d911402c367876871626f";
    const NOISE: &str = "37198a3df5111736b49a68206895669aa64bccaeb567ab018967b3be3a07b112";
    const CT: &str = "4050eb3fa3b4500fb678027da5220421bdb1abfa0faccc7c7f28f00a80697937";
    let coord = coord_int();
    assert_eq!(coord, v.i16s("d2/coord_q14.bin"));
    assert_eq!(hex(&Sha256::digest(i16_to_le(&coord))), COORD);
    let e = v.i16s("d2/row_001328_E_q14_torchpath.bin");
    let hint = hint14(&e);
    assert_eq!(hint, v.i16s("d2/row_001328_hint14_q14.bin"));
    assert_eq!(hex(&Sha256::digest(i16_to_le(&hint))), HINT);
    let c = v.i16s("d2/row_001328_C_q12_cache.bin");
    assert_eq!(hex(&Sha256::digest(i16_to_le(&c))), C_INT);
    let n = v.i16s("d2/row_001328_noise_q12.bin");
    assert_eq!(hex(&Sha256::digest(i16_to_le(&n))), NOISE);
    let (ct, sat) = forward_noise(&c, &n).unwrap();
    assert_eq!(sat, 0);
    assert_eq!(ct, v.i16s("d2/row_001328_Ct_q12.bin"));
    assert_eq!(hex(&Sha256::digest(i16_to_le(&ct))), CT);
}

fn august_session(j: &serde_json::Value, siblings: Vec<[u8; 32]>) -> MembershipWitness {
    let s = &j["session"];
    MembershipWitness {
        protocol_code: 9,
        terminal_committed: 1,
        tree_depth: s["depth"].as_u64().unwrap() as u16,
        row_count: s["rows"].as_u64().unwrap() as u32,
        session_id: s["id"].as_str().unwrap().as_bytes().to_vec(),
        s_0: unhex32(s["s_0"].as_str().unwrap()),
        s_n: unhex32(s["s_n"].as_str().unwrap()),
        authority_manifest_sha256: unhex32(s["authority_manifest_sha256"].as_str().unwrap()),
        chain_log_blake3: unhex32(s["chain_log_blake3"].as_str().unwrap()),
        ordered_session_root_blake3: unhex32(s["ordered_session_root"].as_str().unwrap()),
        siblings_blake3: siblings,
    }
}

fn leaf_from_json(r: &serde_json::Value) -> LeafFields {
    LeafFields {
        row_index: r["t"].as_u64().unwrap() as u32,
        s_t: unhex32(r["s_t"].as_str().unwrap()),
        raw_blake3: unhex32(r["raw_blake3"].as_str().unwrap()),
        meta: unhex(r["meta"].as_str().unwrap()).try_into().unwrap(),
        drand_round: r["drand_round"].as_u64().unwrap(),
        drand_value: unhex32(r["drand_value"].as_str().unwrap()),
        s_next: unhex32(r["s_next"].as_str().unwrap()),
        emission_blake3: unhex32(r["emission_blake3"].as_str().unwrap()),
    }
}

#[test]
fn august_rows_render_open_and_advance() {
    let v = Vectors::open();
    let j = v.json("august/august_rows.json");
    assert_eq!(j["session"]["ordered_session_root"].as_str().unwrap(), "38a484b8793f3afadaf8fc5ba1c04d47e08cdbb4c07a39da09fb4149499a6572");
    let rows = j["rows"].as_object().unwrap();
    assert!(rows.len() >= 7);
    for (key, r) in rows {
        let leaf = leaf_from_json(r);
        // the proved renderer reproduces the chain log's emission digest (and tile_cpu did in Python)
        let (cond, digest) = expand_and_digest(&leaf.s_t);
        assert_eq!(digest, leaf.emission_blake3, "row {key} emission digest");
        // the hint from the same stream equals the pipeline's E_int
        assert_eq!(e_int_torchpath(&cond), v.i16s(&format!("august/row_{:06}_E_q14_torchpath.bin", leaf.row_index)), "row {key} E_int");
        // the leaf opens to the committed root
        let sibs: Vec<[u8; 32]> = r["siblings"].as_array().unwrap().iter().map(|s| unhex32(s.as_str().unwrap())).collect();
        let w = august_session(&j, sibs.clone());
        let ctx = w.context_digest().unwrap();
        assert_eq!(hex(&ctx), j["session"]["context"].as_str().unwrap());
        let lh = row_leaf_hash(&ctx, &leaf);
        assert_eq!(hex(&lh), r["leaf"].as_str().unwrap(), "row {key} leaf");
        assert_eq!(open_to_wrapped_root(&ctx, 712, 10, &lh, leaf.row_index, &sibs).unwrap(), w.ordered_session_root_blake3, "row {key} root");
        // the chain advance of the row reproduces the next state
        let next = b3xof::advance_chain(&leaf.s_t, &leaf.raw_blake3, &leaf.meta, leaf.drand_round, &leaf.drand_value);
        assert_eq!(next, leaf.s_next, "row {key} advance");
    }
    // the byte witnesses for row 600 parse and agree with the JSON
    let h = RowWitnessHeader::parse(&v.bytes("august/row_000600_header_zbroww01.bin")).unwrap();
    assert_eq!(h.row_index, 600);
    assert_eq!(hex(&h.s_t), rows["600"]["s_t"].as_str().unwrap());
    let m = MembershipWitness::parse(&v.bytes("august/row_000600_membership_zbosm001.bin")).unwrap();
    assert_eq!(m.row_count, 712);
    let p = PreviousRecord::parse(&v.bytes("august/row_000600_prev_zbdprv01.bin")).unwrap();
    assert_eq!(b3xof::advance_chain(&p.s_t, &p.raw_blake3, &p.meta, p.drand_round, &p.drand_value), h.s_t);
    for d in [-2_i32, 2, -15, 15, 30] {
        let lu = parse_leaf_u(&v.bytes(&format!("august/row_000600_offset_{d:+}_leaf_u_zbdlfu01.bin"))).unwrap();
        assert_eq!(lu.row_index as i64, 600 + d as i64);
        let su = parse_siblings(&v.bytes(&format!("august/row_000600_offset_{d:+}_siblings_u.bin"))).unwrap();
        let ctx = m.context_digest().unwrap();
        assert_eq!(open_to_wrapped_root(&ctx, 712, 10, &row_leaf_hash(&ctx, &lu), lu.row_index, &su).unwrap(), m.ordered_session_root_blake3);
    }
}

#[test]
fn august_chain_log_walks_end_to_end() {
    let v = Vectors::open();
    let csv = v.bytes("august/chain_log.csv");
    assert_eq!(hex(&blake3p::hash(&csv)), "754e5716e65a065e5ad3146131609a1fd12e8310d966fb6bf2d3de6c568e7f8b");
    let text = String::from_utf8(csv).unwrap();
    let mut lines = text.lines().filter(|l| !l.starts_with('#'));
    let header: Vec<&str> = lines.next().unwrap().split(',').collect();
    let col = |name: &str| header.iter().position(|h| *h == name).unwrap();
    let (c_s, c_b, c_m, c_r, c_v) = (col("S_t_hex"), col("bayer_blake3_hex"), col("meta_hex"), col("drand_round_number"), col("drand_round_value_hex"));
    let rows: Vec<Vec<&str>> = lines.map(|l| l.split(',').collect()).collect();
    assert_eq!(rows.len(), 712);
    let mut ok = 0;
    for t in 0..712 {
        let r = &rows[t];
        let next = b3xof::advance_chain(
            &unhex32(r[c_s]),
            &unhex32(r[c_b]),
            &unhex(r[c_m]).try_into().unwrap(),
            r[c_r].parse().unwrap(),
            &unhex32(r[c_v]),
        );
        let expected = if t + 1 < 712 { unhex32(rows[t + 1][c_s]) } else { unhex32("aeea9f4d6a55ebecd900eae187ea70dce05696551f96ae976c9a5243b3a4398e") };
        if next == expected {
            ok += 1;
        }
    }
    assert_eq!(ok, 712);
}

#[test]
fn august_tree_builder_reproduces_the_frozen_siblings_and_root() {
    use armc_relation::membership::TreeLayers;
    let v = Vectors::open();
    let csv = String::from_utf8(v.bytes("august/chain_log.csv")).unwrap();
    let mut lines = csv.lines().filter(|l| !l.starts_with('#'));
    let header: Vec<&str> = lines.next().unwrap().split(',').collect();
    let col = |name: &str| header.iter().position(|h| *h == name).unwrap();
    let rows: Vec<Vec<&str>> = lines.map(|l| l.split(',').collect()).collect();
    let j = v.json("august/august_rows.json");
    // context_digest validates the witness shape (ten siblings for 712 rows); the values do not enter the context
    let w = august_session(&j, vec![[0_u8; 32]; 10]);
    let ctx = w.context_digest().unwrap();
    let s_n = unhex32(j["session"]["s_n"].as_str().unwrap());
    let leaves: Vec<[u8; 32]> = (0..rows.len())
        .map(|t| {
            let r = &rows[t];
            let leaf = LeafFields {
                row_index: t as u32,
                s_t: unhex32(r[col("S_t_hex")]),
                raw_blake3: unhex32(r[col("bayer_blake3_hex")]),
                meta: unhex(r[col("meta_hex")]).try_into().unwrap(),
                drand_round: r[col("drand_round_number")].parse().unwrap(),
                drand_value: unhex32(r[col("drand_round_value_hex")]),
                s_next: if t + 1 < rows.len() { unhex32(rows[t + 1][col("S_t_hex")]) } else { s_n },
                emission_blake3: unhex32(r[col("emission_live_pixel_blake3_hex")]),
            };
            row_leaf_hash(&ctx, &leaf)
        })
        .collect();
    let tree = TreeLayers::build(&ctx, &leaves).unwrap();
    assert_eq!(tree.depth, 10);
    assert_eq!(hex(&tree.internal_root()), "1d43309ef9a0e2fc6dba98846134280b98cda01840d2204dc41100d5038d3b37");
    assert_eq!(hex(&tree.wrapped_root(&ctx)), "38a484b8793f3afadaf8fc5ba1c04d47e08cdbb4c07a39da09fb4149499a6572");
    // frozen row-96 siblings (native/src/lib.rs SIBLINGS)
    let sib96: Vec<String> = tree.siblings(96).iter().map(|s| hex(s)).collect();
    assert_eq!(sib96[0], "5044e45b95bb454f818d7c6053cd017c88eb63167e00553ffca90fc4db105ea7");
    assert_eq!(sib96[9], "626eacc9816d13823066712b6b8953580e0383460da0ffa0b4a5775501872240");
    // and every row the JSON carries
    for (key, r) in j["rows"].as_object().unwrap() {
        let t: u32 = key.parse().unwrap();
        let expected: Vec<String> = r["siblings"].as_array().unwrap().iter().map(|s| s.as_str().unwrap().to_string()).collect();
        let ours: Vec<String> = tree.siblings(t).iter().map(|s| hex(s)).collect();
        assert_eq!(ours, expected, "row {key} siblings");
        assert_eq!(hex(&leaves[t as usize]), r["leaf"].as_str().unwrap(), "row {key} leaf");
    }
}

#[cfg(feature = "bls")]
#[test]
fn august_rows_599_and_600_beacons_verify() {
    let v = Vectors::open();
    let j = v.json("august/august_rows.json");
    for key in ["599", "600", "602"] {
        let r = &j["rows"][key];
        verify_and_bind(r["drand_round"].as_u64().unwrap(), &unhex(r["drand_signature"].as_str().unwrap()), &unhex32(r["drand_value"].as_str().unwrap()))
            .unwrap_or_else(|e| panic!("row {key}: {e}"));
    }
}

fn e2e_witness(v: &Vectors) -> Witness {
    Witness {
        header: v.bytes("e2e/header_r.bin"),
        membership: v.bytes("e2e/membership_r_zbosm001.bin"),
        raw: synthetic_frame('a'),
        signature: v.bytes("e2e/sig_r.bin"),
        previous: v.bytes("e2e/prev_zbdprv01.bin"),
        leaf_u: v.bytes("e2e/leaf_u_zbdlfu01.bin"),
        siblings_u: v.bytes("e2e/siblings_u.bin"),
        noise: v.bytes("e2e/noise_q12.bin"),
        offset: v.bytes("e2e/offset.bin"),
        offset_rule: vec![OFFSET_RULE_DIRECT],
    }
}

#[cfg(feature = "bls")]
#[test]
fn end_to_end_synthetic_statement_matches_the_python_oracle() {
    let v = Vectors::open();
    let w = e2e_witness(&v);
    let public = evaluate(&w, &StubDenoiser).expect("relation holds on the synthetic session");
    let mut expected = v.bytes("e2e/expected_public_zbdiff01.bin");
    assert_eq!(expected.len(), PUBLIC_BYTES);
    assert!(expected[628..660].iter().all(|&b| b == 0));
    expected[628..660].copy_from_slice(&preprocess_spec_sha256());
    if public != expected {
        let i = public.iter().zip(expected.iter()).position(|(a, b)| a != b).unwrap();
        panic!("public bytes differ at offset {i}: ours {} theirs {}", hex(&public[i..(i + 16).min(PUBLIC_BYTES)]), hex(&expected[i..(i + 16).min(PUBLIC_BYTES)]));
    }
    let p = PublicOutput::parse(&public).unwrap();
    let j = v.json("e2e/e2e.json");
    assert_eq!(p.row_r, j["r"].as_u64().unwrap() as u32);
    assert_eq!(p.row_u, j["u"].as_u64().unwrap() as u32);
    assert_eq!(p.offset, j["offset"].as_i64().unwrap() as i32);
    assert_eq!(p.r_correct, j["R_correct_stub"].as_u64().unwrap());
    assert_eq!(p.r_wrong, j["R_wrong_stub"].as_u64().unwrap());
    assert_eq!(hex(&p.raw_blake3_r), j["raw_blake3"].as_str().unwrap());
    assert_eq!(hex(&p.emission_blake3_u), j["emission_u"].as_str().unwrap());
    assert_eq!(p.denoiser_kind, 0);
    // the intermediate tensors the Python oracle computed
    let c = armc_relation::frame::frame_c_int(&w.raw);
    assert_eq!(c, v.i16s("e2e/C_q12.bin"));
    let (ct, _) = forward_noise(&c, &i16_from_le(&w.noise).unwrap()).unwrap();
    assert_eq!(ct, v.i16s("e2e/Ct_q12.bin"));
    let h = RowWitnessHeader::parse(&w.header).unwrap();
    assert_eq!(hint14(&e_int_torchpath(&b3xof::expand_all(&h.s_t))), v.i16s("e2e/hint_r_q14.bin"));
}

#[cfg(feature = "bls")]
#[test]
fn end_to_end_negative_controls_fail_closed() {
    let v = Vectors::open();
    let w = e2e_witness(&v);
    let ok = evaluate(&w, &StubDenoiser).unwrap();

    let mut t = w.clone();
    t.raw[12_345] ^= 1; // one raw byte: the leaf no longer opens to the root
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "proved row does not open to the committed ordered-session root");

    let mut t = w.clone();
    t.offset = 0_i32.to_le_bytes().to_vec();
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "declared offset must be a nonzero protocol offset");

    let mut t = w.clone();
    t.offset = (-2_i32).to_le_bytes().to_vec(); // a legal offset, but the witnessed leaf is row r+2
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "wrong-row leaf witness does not carry row r + offset");

    let mut t = w.clone();
    t.signature[10] ^= 1;
    assert!(evaluate(&t, &StubDenoiser).is_err());

    let mut t = w.clone();
    t.leaf_u[200] ^= 1; // emission digest of the wrong row
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "declared wrong row's pattern does not render to its leaf's emission digest");

    let mut t = w.clone();
    t.leaf_u[20] ^= 1; // S_u: renders to a different pattern
    assert!(evaluate(&t, &StubDenoiser).is_err());

    let mut t = w.clone();
    t.previous[9] ^= 1; // S_{r-1}: the advance no longer yields S_r
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "previous row's advance does not produce the proved row's S_t");

    let mut t = w.clone();
    t.siblings_u[0] ^= 1;
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "declared wrong row does not open to the committed ordered-session root");

    let mut t = w.clone();
    t.offset_rule = vec![OFFSET_RULE_MIRRORED]; // r = 5, d = +2: the direct wrong row r - d = 3 is inside the 16-row session
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "mirrored offset claimed although the direct wrong row lies inside the session");

    let mut t = w.clone();
    t.offset_rule = vec![2];
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "offset rule flag must be one byte, 0 (direct) or 1 (mirrored)");

    let mut t = w.clone();
    t.offset_rule = Vec::new(); // absent flag reads as direct: byte for byte the same statement
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap(), ok);
    assert_eq!(ok[11], OFFSET_RULE_DIRECT);

    let mut t = w.clone();
    t.noise[0] ^= 1; // a different pinned noise: still a valid statement, with a different digest and residuals
    let other = evaluate(&t, &StubDenoiser).unwrap();
    assert_ne!(other, ok);
    assert_ne!(&other[660..692], &ok[660..692]);
    assert_eq!(&other[0..660], &ok[0..660]);
    assert_eq!(&ok[749..752], &[0, 0, 0], "no clipping event in the synthetic statement");

    // a noise witness at the domain endpoint is admitted (full int16 domain): the statement evaluates and publishes a
    // consistent clip count (the synthetic frame's C lies in [0, 1] Q12, so SA*C + SO*(-32768) stays inside int16 and
    // the count is zero here; the saturating case is the noising_saturation fixture in armc-int/tests/fixtures.rs)
    let mut t = w.clone();
    let plane = OUT_H * OUT_W;
    for k in 0..plane {
        t.noise[2 * k..2 * k + 2].copy_from_slice(&(-32768_i16).to_le_bytes());
    }
    let sat = evaluate(&t, &StubDenoiser).unwrap();
    let p = PublicOutput::parse(&sat).unwrap();
    assert_eq!(sat[749], u8::from(p.clip_events != 0));
    assert_eq!(u16::from_le_bytes([sat[750], sat[751]]), p.clip_events);
    assert_eq!(p.noise_blake3, armc_relation::b3xof::blake3p::hash(&t.noise));
}

#[test]
fn august_row_600_needs_only_the_raw_frame() {
    // Everything for the real August row r = 600, u = 602 is witnessed here except raw_600 (on the node). With a
    // synthetic frame in its place, the relation must fail at exactly the membership leg: the frame's BLAKE3 is
    // not the chain log's, so leaf_r does not open. That is the documented [pending] item.
    let v = Vectors::open();
    let w = Witness {
        header: v.bytes("august/row_000600_header_zbroww01.bin"),
        membership: v.bytes("august/row_000600_membership_zbosm001.bin"),
        raw: synthetic_frame('a'),
        signature: v.bytes("august/row_000600_sig_r.bin"),
        previous: v.bytes("august/row_000600_prev_zbdprv01.bin"),
        leaf_u: v.bytes("august/row_000600_offset_+2_leaf_u_zbdlfu01.bin"),
        siblings_u: v.bytes("august/row_000600_offset_+2_siblings_u.bin"),
        noise: v.bytes("e2e/noise_q12.bin"),
        offset: 2_i32.to_le_bytes().to_vec(),
        offset_rule: vec![OFFSET_RULE_DIRECT],
    };
    #[cfg(feature = "bls")]
    assert_eq!(evaluate(&w, &StubDenoiser).unwrap_err().message(), "proved row does not open to the committed ordered-session root");
    #[cfg(not(feature = "bls"))]
    assert!(evaluate(&w, &StubDenoiser).is_err());
}

// ------------------------------------------------------------------ Astra r5 finding 1: the mirrored -30 offset

/// One row of the August chain log with its beacon signature (the CSV carries `drand_signature_hex` for every row).
struct LogRow {
    s_t: [u8; 32],
    bayer_blake3: [u8; 32],
    meta: [u8; 28],
    drand_round: u64,
    drand_value: [u8; 32],
    signature: Vec<u8>,
}

fn august_log_rows(v: &Vectors) -> Vec<LogRow> {
    let csv = String::from_utf8(v.bytes("august/chain_log.csv")).unwrap();
    let mut lines = csv.lines().filter(|l| !l.starts_with('#'));
    let header: Vec<&str> = lines.next().unwrap().split(',').collect();
    let col = |name: &str| header.iter().position(|h| *h == name).unwrap_or_else(|| panic!("chain log lacks {name}"));
    let (c_s, c_b, c_m, c_r, c_v, c_sig) = (col("S_t_hex"), col("bayer_blake3_hex"), col("meta_hex"), col("drand_round_number"), col("drand_round_value_hex"), col("drand_signature_hex"));
    lines
        .map(|l| {
            let f: Vec<&str> = l.split(',').collect();
            LogRow {
                s_t: unhex32(f[c_s]),
                bayer_blake3: unhex32(f[c_b]),
                meta: unhex(f[c_m]).try_into().unwrap(),
                drand_round: f[c_r].parse().unwrap(),
                drand_value: unhex32(f[c_v]),
                signature: unhex(f[c_sig]),
            }
        })
        .collect()
}

/// A synthetic 40-row session built in Rust from the relation's own primitives: real quicknet beacons borrowed from
/// August rows 600 + t, arbitrary states advanced with the v9 rule, the emission digest of every state rendered, and
/// the tree built with the golden padding rule. Row `MIRROR40_RAW_ROW` commits the BLAKE3 of the frame given. Row 39 has
/// base OFFSETS[39 mod 5] = +30 under the rule anchored at 0, whose direct wrong row 69 lies outside the 40 rows, so its
/// offset is the mirror -30 (u = 9): the -30 case Astra r5 found unreachable in the shipped guest.
struct SyntheticSession {
    membership: armc_relation::membership::MembershipWitness,
    tree: armc_relation::membership::TreeLayers,
    context: [u8; 32],
    root: [u8; 32],
    leaves: Vec<LeafFields>,
    signatures: Vec<Vec<u8>>,
}

const MIRROR40_ROWS: u32 = 40;
const MIRROR40_ID: &[u8] = b"ZBDIFF_SYNTHETIC_MIRROR40_001";
const MIRROR40_RAW_ROW: u32 = 39;

fn build_mirror40(v: &Vectors, raw: &[u8]) -> SyntheticSession {
    use armc_relation::membership::{tree_depth_for_count, TreeLayers};
    let log = august_log_rows(v);
    let n = MIRROR40_ROWS as usize;
    let raw_blake3 = blake3p::hash(raw);
    let s_0 = blake3p::hash(b"ZBDIFF_SYNTHETIC_MIRROR40_001 S_0");
    let mut states = vec![s_0];
    let mut fields: Vec<(u32, [u8; 32], [u8; 28], u64, [u8; 32])> = Vec::new();
    for t in 0..n {
        let src = &log[600 + t];
        let mut meta = [0_u8; 28];
        meta[0..4].copy_from_slice(&(t as u32).to_be_bytes());
        let rb = if t as u32 == MIRROR40_RAW_ROW { raw_blake3 } else { blake3p::hash(format!("ZBDIFF_SYNTHETIC_MIRROR40 raw {t}").as_bytes()) };
        let next = b3xof::advance_chain(&states[t], &rb, &meta, src.drand_round, &src.drand_value);
        states.push(next);
        fields.push((t as u32, rb, meta, src.drand_round, src.drand_value));
    }
    let s_n = states[n];
    let depth = tree_depth_for_count(MIRROR40_ROWS).unwrap();
    let mut membership = armc_relation::membership::MembershipWitness {
        protocol_code: 9,
        terminal_committed: 1,
        tree_depth: depth,
        row_count: MIRROR40_ROWS,
        session_id: MIRROR40_ID.to_vec(),
        s_0,
        s_n,
        authority_manifest_sha256: Sha256::digest(b"ZBDIFF_SYNTHETIC_MIRROR40_001 authority manifest").into(),
        chain_log_blake3: blake3p::hash(b"ZBDIFF_SYNTHETIC_MIRROR40_001 chain log"),
        ordered_session_root_blake3: [0; 32],
        siblings_blake3: vec![[0; 32]; usize::from(depth)],
    };
    let context = membership.context_digest().unwrap();
    let leaves: Vec<LeafFields> = fields
        .iter()
        .map(|&(t, rb, meta, round, value)| LeafFields {
            row_index: t,
            s_t: states[t as usize],
            raw_blake3: rb,
            meta,
            drand_round: round,
            drand_value: value,
            s_next: states[t as usize + 1],
            emission_blake3: expand_and_digest(&states[t as usize]).1,
        })
        .collect();
    let hashes: Vec<[u8; 32]> = leaves.iter().map(|l| row_leaf_hash(&context, l)).collect();
    let tree = TreeLayers::build(&context, &hashes).unwrap();
    let root = tree.wrapped_root(&context);
    membership.ordered_session_root_blake3 = root;
    membership.siblings_blake3 = Vec::new();
    let signatures = (0..n).map(|t| log[600 + t].signature.clone()).collect();
    SyntheticSession { membership, tree, context, root, leaves, signatures }
}

impl SyntheticSession {
    fn witness(&self, r: u32, d: i32, flag: u8, raw: Vec<u8>, noise: Vec<u8>) -> Witness {
        use armc_relation::membership::encode_leaf_u;
        // an out-of-range u (a refusal case) gets row 0's leaf: the guest refuses before it reads leaf_u
        let u_i64 = r as i64 + d as i64;
        let u = if (0..MIRROR40_ROWS as i64).contains(&u_i64) { u_i64 as u32 } else { 0 };
        let lr = &self.leaves[r as usize];
        let prev = &self.leaves[r as usize - 1];
        let header = RowWitnessHeader { row_index: r, s_t: lr.s_t, meta: lr.meta, drand_round: lr.drand_round, drand_value: lr.drand_value }.encode().unwrap().to_vec();
        let mut m = self.membership.clone();
        m.siblings_blake3 = self.tree.siblings(r);
        let previous = PreviousRecord {
            s_t: prev.s_t,
            raw_blake3: prev.raw_blake3,
            meta: prev.meta,
            drand_round: prev.drand_round,
            drand_value: prev.drand_value,
            signature: self.signatures[r as usize - 1].clone().try_into().unwrap(),
        };
        Witness {
            header,
            membership: m.encode().unwrap(),
            raw,
            signature: self.signatures[r as usize].clone(),
            previous: previous.encode(),
            leaf_u: encode_leaf_u(&self.leaves[u as usize]),
            siblings_u: self.tree.siblings(u).iter().flat_map(|s| s.iter().copied()).collect(),
            noise,
            offset: d.to_le_bytes().to_vec(),
            offset_rule: vec![flag],
        }
    }
}

/// The frame the synthetic mirror session commits: August frame 600 when it is on this box (the development machine, the node), else
/// synthetic frame a. Returns the bytes and the `--raw` spec the executor needs.
fn mirror40_frame() -> (Vec<u8>, String) {
    let p = vectors_dir().join("../frames_august/frame_000600.raw");
    match std::fs::read(&p) {
        Ok(b) if b.len() == RAW_BYTES => (b, p.canonicalize().unwrap().display().to_string()),
        _ => (synthetic_frame('a'), "synthetic:a".into()),
    }
}

fn mirror40_noise(v: &Vectors) -> (Vec<u8>, String) {
    let p = vectors_dir().join("../noise_august/noise_000684.i16");
    match std::fs::read(&p) {
        Ok(b) if b.len() == 86_016 => (b, "noise_august/noise_000684.i16 (the normative noise of the real -30 row 684)".into()),
        _ => (v.bytes("e2e/noise_q12.bin"), "e2e/noise_q12.bin".into()),
    }
}

#[cfg(feature = "bls")]
#[test]
fn synthetic_mirror40_session_admits_the_mirrored_minus_30_statement_and_refuses_its_relabellings() {
    let v = Vectors::open();
    let (raw, raw_spec) = mirror40_frame();
    let (noise, noise_src) = mirror40_noise(&v);
    let s = build_mirror40(&v, &raw);
    // positive: row 39, base +30 -> 69 outside the 40-row session -> mirrored -30 -> u = 9
    let a = armc_relation::rule::assignment(MIRROR40_RAW_ROW, 0, MIRROR40_ROWS).unwrap();
    assert_eq!((a.base, a.offset, a.mirrored, a.wrong_row), (30, -30, true, 9));
    let w = s.witness(39, -30, OFFSET_RULE_MIRRORED, raw.clone(), noise.clone());
    let public = evaluate(&w, &StubDenoiser).expect("the mirrored -30 statement holds on the synthetic session");
    let p = PublicOutput::parse(&public).unwrap();
    assert_eq!((p.row_r, p.row_u, p.offset, p.offset_rule), (39, 9, -30, OFFSET_RULE_MIRRORED));
    assert_eq!(public[11], 1);
    assert_eq!(p.row_count, MIRROR40_ROWS);
    assert_eq!(p.ordered_session_root, s.root);
    assert_eq!(p.context_digest, s.context);
    assert_eq!(p.raw_blake3_r, blake3p::hash(&raw));
    assert_eq!(p.noise_blake3, blake3p::hash(&noise));
    assert_eq!(p.leaf_u, row_leaf_hash(&s.context, &s.leaves[9]));

    // the relabellings of the same witness that the guest must refuse
    let mut t = w.clone();
    t.offset_rule = vec![OFFSET_RULE_DIRECT]; // -30 as a direct claim
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "declared offset must be a nonzero protocol offset");
    let mut t = w.clone();
    t.offset = 30_i32.to_le_bytes().to_vec(); // +30 under the mirror flag: its base would be -30, not a protocol offset
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "mirrored offset must be the mirror of a protocol offset");
    // a mirror flag on a row whose direct wrong row exists (row 20, -2 mirrored: base +2 -> 22 inside) is refused
    let w20 = s.witness(20, -2, OFFSET_RULE_MIRRORED, raw.clone(), noise.clone());
    assert_eq!(evaluate(&w20, &StubDenoiser).unwrap_err().message(), "mirrored offset claimed although the direct wrong row lies inside the session");
    let mut t = w.clone();
    t.offset = (-15_i32).to_le_bytes().to_vec(); // mirrored -15 at row 39: base +15 -> 54 outside, so generically admissible, but the leaf is row 9's
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "wrong-row leaf witness does not carry row r + offset");
    // a row whose direct +30 exists (row 3 -> 33) may not claim the mirror
    let w3 = s.witness(3, -30, OFFSET_RULE_MIRRORED, raw.clone(), noise.clone());
    assert_eq!(evaluate(&w3, &StubDenoiser).unwrap_err().message(), "declared wrong row is outside the committed session");
    let w9 = s.witness(9, 30, OFFSET_RULE_DIRECT, raw.clone(), noise.clone());
    assert_eq!(evaluate(&w9, &StubDenoiser).unwrap_err().message(), "proved row does not open to the committed ordered-session root", "row 9 does not commit this frame");
    // the same row with a legal direct offset and its own frame digest is a different, valid statement (policy, not
    // the guest, says row 39's offset is the mirrored -30)
    let w_direct = s.witness(39, -15, OFFSET_RULE_DIRECT, raw.clone(), noise.clone());
    let pd = PublicOutput::parse(&evaluate(&w_direct, &StubDenoiser).unwrap()).unwrap();
    assert_eq!((pd.row_u, pd.offset, pd.offset_rule), (24, -15, OFFSET_RULE_DIRECT));

    // write the mirrored witness for the executor (complete guest, real network): vectors_relation/synthetic_mirror40/
    let out = vectors_dir().join("synthetic_mirror40");
    std::fs::create_dir_all(&out).unwrap();
    for (name, bytes) in [
        ("header_r.bin", &w.header),
        ("membership_r_zbosm001.bin", &w.membership),
        ("sig_r.bin", &w.signature),
        ("prev_zbdprv01.bin", &w.previous),
        ("leaf_u_zbdlfu01.bin", &w.leaf_u),
        ("siblings_u.bin", &w.siblings_u),
        ("noise_q12.bin", &w.noise),
        ("offset.bin", &w.offset),
        ("offset_rule.bin", &w.offset_rule),
    ] {
        std::fs::write(out.join(name), bytes).unwrap();
    }
    let info = serde_json::json!({
        "what": "synthetic 40-row session built by relation/tests/vectors.rs (build_mirror40): real quicknet beacons of August rows 600..639, arbitrary states advanced by the v9 rule, every emission rendered, golden padding tree; row 39 commits the frame below and claims the mirrored -30 offset (base OFFSETS[39 mod 5] = +30 -> 69 outside), u = 9",
        "session_id": String::from_utf8_lossy(MIRROR40_ID),
        "rows": MIRROR40_ROWS,
        "tree_depth": s.tree.depth,
        "context_digest": hex(&s.context),
        "ordered_session_root": hex(&s.root),
        "r": 39, "u": 9, "offset": -30, "offset_rule": "mirrored",
        "raw": raw_spec,
        "raw_sha256": hex(&Sha256::digest(&raw)),
        "raw_blake3": hex(&blake3p::hash(&raw)),
        "noise": noise_src,
        "noise_sha256": hex(&Sha256::digest(&noise)),
        "noise_blake3": hex(&blake3p::hash(&noise)),
        "stub_public_sha256": hex(&Sha256::digest(&public)),
        "stub_r_correct": p.r_correct, "stub_r_wrong": p.r_wrong,
        "executor": "zkdiff-execute --witness-dir vectors_relation/synthetic_mirror40 --raw <raw> --blob blobs/final_int16/constants_int16.blob",
    });
    std::fs::write(out.join("synthetic_mirror40.json"), serde_json::to_string_pretty(&info).unwrap()).unwrap();
}

#[test]
fn august_row_684_mirrored_minus_30_passes_the_offset_check_and_needs_only_its_frame() {
    // The prepared witness of the real -30 row (zkdiff-batch prepare, runs/batch_prepare_g2d_20260907/row_000684/witness):
    // with a substitute frame the relation must fail exactly at the membership leg, i.e. AFTER the offset check that
    // the shipped guest failed at (Astra r5 finding 1). The complete execute waits for the frame on the node [pending node].
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../runs/batch_prepare_g2d_20260907/row_000684/witness");
    let read = |n: &str| std::fs::read(dir.join(n)).unwrap_or_else(|e| panic!("{}: {e}", dir.join(n).display()));
    let w = Witness {
        header: read("header_r.bin"),
        membership: read("membership_r_zbosm001.bin"),
        raw: synthetic_frame('a'),
        signature: read("sig_r.bin"),
        previous: read("prev_zbdprv01.bin"),
        leaf_u: read("leaf_u_zbdlfu01.bin"),
        siblings_u: read("siblings_u.bin"),
        noise: read("noise_q12.bin"),
        offset: read("offset.bin"),
        offset_rule: read("offset_rule.bin"),
    };
    assert_eq!(i32::from_le_bytes(w.offset.clone().try_into().unwrap()), -30);
    assert_eq!(w.offset_rule, vec![OFFSET_RULE_MIRRORED]);
    assert_eq!(RowWitnessHeader::parse(&w.header).unwrap().row_index, 684);
    assert_eq!(parse_leaf_u(&w.leaf_u).unwrap().row_index, 654);
    #[cfg(feature = "bls")]
    assert_eq!(evaluate(&w, &StubDenoiser).unwrap_err().message(), "proved row does not open to the committed ordered-session root");
    #[cfg(not(feature = "bls"))]
    assert!(evaluate(&w, &StubDenoiser).is_err());
    // and the two relabellings are refused before any frame is touched
    let mut t = w.clone();
    t.offset_rule = vec![OFFSET_RULE_DIRECT];
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "declared offset must be a nonzero protocol offset");
    let mut t = w.clone();
    t.offset = 30_i32.to_le_bytes().to_vec();
    assert_eq!(evaluate(&t, &StubDenoiser).unwrap_err().message(), "mirrored offset must be the mirror of a protocol offset");
}
